# Generated by Django 3.2.8 on 2021-10-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlight', '0002_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='percent',
            field=models.IntegerField(default=None, null=True, verbose_name='Процент освещенности'),
        ),
    ]
